parameters:
    carlo94it.seosearchtags.search_engines:
        - { host: google.com, query: q }
        - { host: google.it, query: q }
        - { host: search.yahoo.com, query: p }
        - { host: it.search.yahoo.com, query: p }
        - { host: bing.com, query: q }
        - { host: yauba.com, query: q }
        - { host: it.yauba.com, query: q }
