parameters:
    carlo94it.seosearchtags.search_engines:
        - google.com: q
        - google.it: q
        - search.yahoo.com: p
        - it.search.yahoo.com: p
        - bing.com: q
        - yauba.com: q
        - it.yauba.com: q
